version: '3.8'
services:
  react-app:
    build: .
    ports:
      - "5173:5173" # Vite.js utilise le port 5173
    volumes:
      - .:/app
      - /app/node_modules # Empêche le conflit entre les dépendances locales et celles du conteneur
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true 